[package]
name = "beautiful_morning"
version = "0.1.0"
authors = ["Talos208 <talos208@gmail.com>"]

[dependencies]
nickel="*"
rustc-serialize = "0.3"
chrono={version = "0.3", features = ["rustc-serialize"]}
rust-crypto = "*"
jwt = "*"
hyper = "0.9.18"